package com.cybele.semanticenrichment.repository;

import java.util.List;
import java.util.Map;

import com.github.jsonldjava.shaded.com.google.common.collect.ImmutableMap;

public final class SPARQL_URIs {
		
	 public static final String ACCRUAL_PERIODICITY="ACCRUAL_PERIODICITY";
	 public static final String LANGUAGE="LANGUAGE";
	 public static final String COUNTRY="COUNTRY";
	 public static final String AGENT="AGENT";
	 public static final String LICENSE="LICENSE";
	 public static final String MEDIA_TYPE="MEDIA_TYPE";
	
	 public static final Map<String, String> CODELISTS = ImmutableMap.of(
			  ACCRUAL_PERIODICITY, "<http://purl.org/cld/terms/Frequency>",
		      LANGUAGE, "<http://publications.europa.eu/resource/authority/language>",
		      COUNTRY, "<http://publications.europa.eu/resource/authority/country>",
		      LICENSE, "<http://publications.europa.eu/resource/authority/licence>",
 		      MEDIA_TYPE,"<http://publications.europa.eu/resource/authority/file-type>");
	 
	 public static final List<String> MEASURE_COMPONENTS = List.of(
			 "crop__pesticideRawCost",
			 "crop__tillageCost",
			 "pigMeatQuality__muscleDrip",
			 "pigMeatQuality__intraMuscularFat",
			 "pigWeighing__minimumWeight",
			 "pigMeatQuality__crudeProtein",
			 "pigWeighing__meanWeight",
			 "field__calculatedArea",
			 "foodIncidence__incidencesNumber",
			 "pigWeighing__distinctWeightMeasurement",
			 "pigFeedingBehavior__feedIntake",
			 "pigFeedingBehavior__feedingWeight",
			 "pigFeedingBehavior__feedingDuration",
			 "weather__averageRelativeHumidity",
			 "fish_prob",
			 "weather__effectivePrecipitation",
			 "pigMeatQuality__carcassCompositionMeasure_4",
			 "pigMeatQuality__carcassCompositionMeasure_3",
			 "pigMeatQuality__carcassCompositionMeasure_2",
			 "pigMeatQuality__carcassCompositionMeasure_1",
			 "pigMeatQuality__fatThickness",
			 "pigMeatQuality__meatPercentage",
			 "pigMeatQuality__rejectedWeight",
			 "pigMeatQuality__carcassWeight",
			 "pigProfile__veterinaryInspection_3",
			 "pigProfile__veterinaryInspection_2",
			 "pigProfile__veterinaryInspection_1",
			 "crop__chlorophyllIndexGreen",
			 "crop__diseaseWaterStressIndex",
			 "crop__enhancedVegetationIndex",
			 "crop__fertiliserAmount",
			 "crop__fertiliserCost",
			 "crop__fertiliserRawCost",
			 "crop__harvestCost",
			 "crop__irrigationCost",
			 "crop__manureAmount",
			 "crop__modifiedNormalizedDifferenceVegetationIndex",
			 "crop__moistureStressIndex",
			 "crop__normalizedDifferenceVegetationIndex",
			 "crop__pesticideAmount",
			 "crop__pesticideCost",
			 "crop__proteinOutput",
			 "crop__revenue",
			 "crop__seedRawCost",
			 "crop__seedUnits",
			 "crop__sellPrice",
			 "crop__soilAdjustedVegetationIndex",
			 "crop__sowingCost",
			 "crop__yieldOutput",
			 "field__firstDayPredictionProbability",
			 "field__secondDayPredictionProbability",
			 "fishingSale__saleKiloPrice",
			 "fishingSale__saleTotalValue",
			 "fishingSale__saleWeight",
			 "fishingTrip__landingWeight",
			 "fishingTrip__vesselGrossTonage",
			 "openSeaFishing__fishingHours",
			 "openSeaFishing__vesselEnginePower",
			 "openSeaFishing__vesselSpeed",
			 "pigFarmingConditions__averageTemperatureHumidityIndex",
			 "pigFarmingConditions__sensorBatteryLife",
			 "pigFarmingConditions__sensorBatteryVoltage",
			 "pigFarmingConditions__sensorFormattedHumidity",
			 "pigFarmingConditions__sensorFormattedLuminosity",
			 "pigFarmingConditions__sensorFormattedTemperature",
			 "pigFarmingConditions__sensorHumidity",
			 "pigFarmingConditions__sensorLuminosity",
			 "pigFarmingConditions__sensorSignalStrength",
			 "pigFarmingConditions__sensorTemperature",
			 "pigFeedingBehavior__consecutiveDrinkerVisitsAverageTimeGap",
			 "pigFeedingBehavior__consecutiveFeederVisitsAverageTimeGap",
			 "pigFeedingBehavior__groupLastHourDrinkIntake",
			 "pigFeedingBehavior__groupLastHourDrinkerDuration",
			 "pigFeedingBehavior__groupLastHourDrinkerRegistrations",
			 "pigFeedingBehavior__groupLastHourDrinkerVisits",
			 "pigFeedingBehavior__groupLastHourFeedIntake",
			 "pigFeedingBehavior__groupLastHourFeederDuration",
			 "pigFeedingBehavior__groupLastHourFeederRegistrations",
			 "pigFeedingBehavior__groupLastHourFeederVisits",
			 "pigFeedingBehavior__individualLastHourDrinkIntake",
			 "pigFeedingBehavior__individualLastHourDrinkerDuration",
			 "pigFeedingBehavior__individualLastHourDrinkerRegistrations",
			 "pigFeedingBehavior__individualLastHourDrinkerVisits",
			 "pigFeedingBehavior__individualLastHourFeedIntake",
			 "pigFeedingBehavior__individualLastHourFeederDuration",
			 "pigFeedingBehavior__individualLastHourFeederRegistrations",
			 "pigFeedingBehavior__individualLastHourFeederVisits",
			 "pigFeedingBehavior__visitCycles",
			 "pigMeatQuality__carcassCompositionMeasure",
			 "pigMeatQuality__cielabValueA",
			 "pigMeatQuality__cielabValueB",
			 "pigMeatQuality__cielabValueL",
			 "pigMeatQuality__cookingLoss",
			 "pigMeatQuality__dryMatter",
			 "pigMeatQuality__meatMoisture",
			 "pigMeatQuality__reflectionValue",
			 "pigMeatQuality__sampleNumber",
			 "pigMeatQuality__sarcomereLength",
			 "pigMeatQuality__scanValueA",
			 "pigMeatQuality__scanValueB",
			 "pigMeatQuality__scanValueL",
			 "pigMeatQuality__scanValuePH",
			 "pigMeatQuality__scanValuePH1",
			 "pigMeatQuality__scanValuePH24",
			 "pigMeatQuality__shearForce",
			 "pigMeatQuality__solubleCollagen",
			 "pigMeatQuality__thawingLoss",
			 "pigMeatQuality__totalCollagen",
			 "pigProfile__relatedPigWeighing",
			 "pigProfile__veterinaryInspection",
			 "pigWeighing__maximumWeight",
			 "pigWeighing__meanWeightGroup",
			 "pigWeighing__standardDeviationWeight",
			 "weather__accumulatedRainPrecipitation",
			 "weather__actualEvapotranspiration",
			 "weather__averageAirTemperature",
			 "weather__landSurfaceTemperature",
			 "weather__maximumAirTemperature",
			 "weather__maximumRelativeHumidity",
			 "weather__maximumWindSpeed",
			 "weather__maximumWindSpeedDirection",
			 "weather__minimumAirTemperature",
			 "weather__minimumRelativeHumidity",
			 "weather__potentialEvapotranspiration",
			 "weather__solarRadiation",
			 "weather__solarRadiationReflection",
			 "weather__windSpeed",
			 "weather__windSpeedDirection",
			 "Battery",
			 "Humidity",
			 "Illuminance",
			 "Signal_Strength",
			 "Temperature",
			 "Voltage",
			 "duration",
			 "feed_intake",
			 "weight"
			 );
}